Repository kyma-project/module-manager, pull requests merged in 2022-12, with the labels that each got.

#192 feat: pointer of installinfo and postrun hooks
  controllers/manifest_controller.go
  controllers/workers.go
  internal/pkg/custom/verify.go
  internal/pkg/prepare/deploy.go
  pkg/applier/ssa.go
  pkg/client/factory.go
  pkg/declarative/options.go
  pkg/declarative/reconciler.go
  pkg/manifest/helm_processor.go
  pkg/manifest/kustomize_processor.go
  pkg/manifest/operations.go
  pkg/manifest/renderer_cache_test.go
  pkg/resource/operations.go
  pkg/types/applier.go
  pkg/types/check_fn.go
  pkg/types/declaritive.go
  pkg/types/installs.go
Labels: lgtm, size/L

#195 Make sure module crs get deleted before module operator
  controllers/suite_test.go
  pkg/manifest/helm_processor.go
  pkg/manifest/operations.go
  pkg/manifest/operations_test.go
  pkg/resource/operations.go
  pkg/types/installs.go
Labels: lgtm, size/L

#196 Fix uninstallation bugs in decliarative library
  pkg/manifest/helm_processor.go
  pkg/manifest/helm_processor_util.go
  pkg/manifest/operations.go
  pkg/types/installs.go
Labels: lgtm, size/L

#197 Decrease cpu/memory requests for module manager
  config/manager/manager.yaml
Labels: lgtm, size/XS

#198 fix: add ci mode to module manager deploy
  .github/workflows/ci.yml
Labels: lgtm, size/XS

#194 Declarative v2
  config/crd/bases/test.declarative.kyma-project.io_testapis.yaml
  go.mod
  go.sum
  pkg/client/client_proxy.go
  pkg/client/factory.go
  pkg/client/util.go
  pkg/declarative/v2/cleanup.go
  pkg/declarative/v2/client.go
  pkg/declarative/v2/client_cache.go
  pkg/declarative/v2/crds.go
  pkg/declarative/v2/default_transforms.go
  pkg/declarative/v2/default_transforms_test.go
  pkg/declarative/v2/helm.go
  pkg/declarative/v2/kustomize.go
  pkg/declarative/v2/mock/object.go
  pkg/declarative/v2/object.go
  pkg/declarative/v2/options.go
  pkg/declarative/v2/raw_render.go
  pkg/declarative/v2/raw_render_test.go
  pkg/declarative/v2/ready_check.go
  pkg/declarative/v2/reconciler.go
  pkg/declarative/v2/renderer.go
  pkg/declarative/v2/renderer_with_cache.go
  pkg/declarative/v2/renderer_with_cache_test.go
  pkg/declarative/v2/resource_converter.go
  pkg/declarative/v2/spec.go
  pkg/declarative/v2/ssa.go
  pkg/declarative/v2/ssa_test.go
  pkg/declarative/v2/test/v1/api.go
  pkg/declarative/v2/test/v1/declarative_test.go
  pkg/declarative/v2/test/v1/helper_test.go
  pkg/declarative/v2/test/v1/suite_test.go
  pkg/declarative/v2/test/v1/zz_generated.deepcopy.go
  pkg/declarative/v2/zz_generated.deepcopy.go
  pkg/manifest/helm_processor.go
  pkg/manifest/helm_processor_util.go
  pkg/manifest/operations.go
  pkg/test_samples/module-chart/.helmignore
  pkg/test_samples/module-chart/Chart.yaml
  pkg/test_samples/module-chart/templates/NOTES.txt
  pkg/test_samples/module-chart/templates/_helpers.tpl
  pkg/test_samples/module-chart/templates/deployment.yaml
  pkg/test_samples/module-chart/templates/hpa.yaml
  pkg/test_samples/module-chart/templates/ingress.yaml
  pkg/test_samples/module-chart/templates/service.yaml
  pkg/test_samples/module-chart/templates/serviceaccount.yaml
  pkg/test_samples/module-chart/templates/tests/test-connection.yaml
  pkg/test_samples/module-chart/values.yaml
  pkg/test_samples/raw-manifest.yaml
  pkg/types/declaritive.go
  pkg/util/util.go
Labels: lgtm, size/XXL
