Repository kyma-project/module-manager, pull requests merged in 2022-11, with the labels that each got.

#160 fix: FS cached manifest permissions error resilience
  operator/controllers/manifest_controller.go
  operator/pkg/manifest/operations.go
Labels: lgtm, size/S

#162 Skip Caching if Cache-Key is missing
  operator/controllers/manifest_controller.go
  operator/pkg/labels/component_labels.go
  operator/pkg/manifest/operations.go
  operator/pkg/util/util.go
Labels: lgtm, size/M

#163 tests: FS cached manifest permissions error resilience
  operator/controllers/manifest_controller_test.go
  operator/controllers/suite_test.go
  operator/pkg/descriptor/parse.go
  operator/pkg/manifest/helm_processor.go
  operator/pkg/manifest/kustomize_processor.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/rendered.go
  operator/pkg/manifest/transform.go
  operator/pkg/types/file_error.go
  operator/pkg/types/installs.go
  operator/pkg/util/util.go
Labels: size/XL, lgtm

#169 Adjust GH Action regarding pipelines
  .github/workflows/ci.yml
Labels: lgtm, size/XS

#165 feat | fix : manifest processor config and rendered manifest invalidation
  .gitignore
  operator/controllers/client_cache_manager.go
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_controller_helper_test.go
  operator/controllers/manifest_controller_test.go
  operator/controllers/suite_test.go
  operator/controllers/workers.go
  operator/internal/pkg/types/types.go
  operator/internal/pkg/util/util.go
  operator/pkg/applier/ssa.go
  operator/pkg/manifest/helm_processor.go
  operator/pkg/manifest/kustomize_processor.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/rendered.go
  operator/pkg/manifest/renderer_cache.go
  operator/pkg/manifest/renderer_cache_test.go
  operator/pkg/manifest/suite_test.go
  operator/pkg/test_samples/helm/.helmignore
  operator/pkg/test_samples/helm/Chart.yaml
  operator/pkg/test_samples/helm/templates/deployment.yaml
  operator/pkg/test_samples/helm/templates/service.yaml
  operator/pkg/test_samples/helm/values.yaml
  operator/pkg/test_samples/kustomize/cr.yaml
  operator/pkg/test_samples/kustomize/crd.yaml
  operator/pkg/test_samples/kustomize/kustomization.yaml
  operator/pkg/test_samples/oci/compressed.tgz
  operator/pkg/types/applier.go
  operator/pkg/types/cache.go
  operator/pkg/types/installs.go
  operator/pkg/util/util.go
Labels: size/XL, lgtm

#167 fix: attempt to install on helm consistency check to replicate old reconciler behavior
  operator/.golangci.yaml
  operator/Makefile
  operator/config/load_test/kustomization.yaml
  operator/config/load_test/patches/adjust_resources_in_deployment.yaml
  operator/config/watcher/kustomization.yaml
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_controller_test.go
  operator/controllers/suite_test.go
  operator/controllers/workers.go
  operator/go.mod
  operator/go.sum
  operator/internal/pkg/custom/verify.go
  operator/internal/pkg/util/util.go
  operator/main.go
  operator/pkg/applier/ssa.go
  operator/pkg/client/client_factory.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/helm_processor.go
  operator/pkg/manifest/helm_processor_util.go
  operator/pkg/manifest/kustomize_processor.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/rendered.go
  operator/pkg/manifest/renderer_cache_test.go
  operator/pkg/manifest/repo.go
  operator/pkg/manifest/transform.go
  operator/pkg/ratelimit/jitter.go
  operator/pkg/ratelimit/jitter_test.go
  operator/pkg/resource/operations.go
  operator/pkg/rest/getter.go
  operator/pkg/types/check_fn.go
  operator/pkg/types/multi_error.go
Labels: lgtm, size/XXL

#173 chore: fixup integration test
  .github/workflows/ci.yml
Labels: lgtm, size/XS

#172 fix: error state handing + logging on error
  .github/workflows/ci.yml
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_controller_test.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/helm_processor.go
  operator/pkg/manifest/operations.go
Labels: lgtm, size/M

#178 Fix declarative manifest caching that was not invalidated
  operator/controllers/manifest_controller.go
  operator/pkg/cache/client_cache_manager.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/renderer_cache_test.go
Labels: lgtm, size/L

#181 Corrected links to the template-operator
  README.md
Labels: lgtm, size/XS

#166 Refact tests
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_controller_helper_test.go
  operator/controllers/manifest_controller_test.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/pkg/prepare/deploy.go
  operator/main.go
  operator/pkg/log/logger.go
  operator/pkg/resource/operations.go
Labels: size/XL, lgtm

#184 remove cached manifest in uninstall process
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/rendered.go
  operator/pkg/types/installs.go
Labels: lgtm, size/S

#185 refactor: re-introduce missing use cases for tests
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_controller_helper_test.go
  operator/controllers/manifest_controller_test.go
  operator/internal/pkg/prepare/deploy.go
  operator/pkg/client/util.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/renderer_cache_test.go
  operator/pkg/test_samples/kustomize/cr.yaml
  operator/pkg/test_samples/kustomize/crd.yaml
  operator/pkg/types/file_error.go
Labels: lgtm, size/L

#180 fix: CR mappings for helm CRDs
  operator/controllers/manifest_controller_helper_test.go
  operator/controllers/manifest_controller_test.go
  operator/pkg/applier/ssa.go
  operator/pkg/client/client_proxy.go
  operator/pkg/client/factory.go
  operator/pkg/client/kube_factory_proxy.go
  operator/pkg/client/util.go
  operator/pkg/manifest/helm_processor.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/rendered.go
  operator/pkg/resource/operations.go
  operator/pkg/test_samples/helm/crds/sample_crd.yaml
  operator/pkg/test_samples/helm/templates/sample_cr.yaml
  operator/pkg/test_samples/oci/compressed.tgz
  operator/pkg/test_samples/oci/helm_chart_with_crds.tgz
  operator/pkg/types/multi_error.go
  operator/pkg/util/util.go
Labels: lgtm, size/L
