Repository kyma-project/module-manager, pull requests merged in 2022-07, with the labels that each got.

#31 Add jitter
  operator/controllers/jitter.go
  operator/controllers/jitter_test.go
  operator/controllers/manifest_controller.go
Labels: lgtm

#33 API changes for overrides + sync
  api/api/v1alpha1/manifest_types.go
  api/api/v1alpha1/zz_generated.deepcopy.go
  api/config/crd/bases/component.kyma-project.io_manifests.yaml
Labels: lgtm

#34 connect overrides from --set flag
  operator/controllers/manifest_controller.go
  operator/controllers/remote.go
  operator/go.mod
  operator/go.sum
  operator/pkg/manifest/operations.go
Labels: lgtm

#35 Handle OCI Image layers
  api/Makefile
  api/api/v1alpha1/manifest_types.go
  api/api/v1alpha1/zz_generated.deepcopy.go
  api/config/crd/bases/component.kyma-project.io_manifests.yaml
  api/go.mod
  api/go.sum
  operator/Makefile
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_util.go
  operator/go.mod
  operator/go.sum
  operator/pkg/descriptor/parse.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/crd.go
  operator/pkg/manifest/operations.go
Labels: lgtm

#37 For load test
  operator/Dockerfile
  operator/config/default/kustomization.yaml
  operator/config/default/manager_auth_proxy_patch.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/kustomization.yaml
  operator/config/rbac/metrics_cluster_role_binding.yaml
  operator/config/rbac/metrics_role.yaml
  operator/config/rbac/metrics_role_binding.yaml
  operator/go.mod
  operator/go.sum
  operator/main.go
Labels: lgtm

#42 feat: API changes for overrides & chart types
  api/api/v1alpha1/manifest_types.go
  api/api/v1alpha1/zz_generated.deepcopy.go
  api/config/crd/bases/component.kyma-project.io_manifests.yaml
  api/config/samples/component_v1alpha1_manifest.yaml
Labels: lgtm, size/L

#44 feat: API webhooks and codec
  api/PROJECT
  api/api/v1alpha1/manifest_types.go
  api/api/v1alpha1/manifest_webhook.go
  api/api/v1alpha1/validator.go
  api/api/v1alpha1/webhook_suite_test.go
  api/config/certmanager/certificate.yaml
  api/config/certmanager/kustomization.yaml
  api/config/certmanager/kustomizeconfig.yaml
  api/config/default/manager_webhook_patch.yaml
  api/config/default/webhookcainjection_patch.yaml
  api/config/samples/component_v1alpha1_manifest.yaml
  api/config/webhook/kustomization.yaml
  api/config/webhook/kustomizeconfig.yaml
  api/config/webhook/manifests.yaml
  api/config/webhook/service.yaml
  api/go.mod
  api/go.sum
Labels: size/XL, lgtm

#43 feat: handle chart validation
  operator/controllers/config_mgt.go
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_util.go
  operator/go.mod
  operator/go.sum
  operator/main.go
Labels: lgtm, size/L

#46 feat: Handle overrides from config maps
  api/config/samples/component_v1alpha1_manifest.yaml
  api/config/samples/config-map-override.yaml
  operator/controllers/config_mgt.go
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_util.go
  operator/main.go
  operator/pkg/descriptor/parse.go
  operator/pkg/labels/component_labels.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
Labels: size/XL, lgtm

#54 chore: Remove default config as fallback, optional resource and others
  operator/api/v1alpha1/manifest_types.go
  operator/config/crd/bases/component.kyma-project.io_manifests.yaml
  operator/config/crd/bases/sample_crd.yaml
  operator/config/samples/component_v1alpha1_manifest.yaml
  operator/controllers/manifest_controller.go
  operator/internal/pkg/custom/verify.go
  operator/internal/pkg/prepare/deploy.go
  operator/pkg/custom/client.go
  operator/pkg/custom/function.go
  operator/pkg/custom/status.go
  operator/pkg/manifest/operations.go
Labels: lgtm, size/L
