Repository kyma-project/module-manager, pull requests merged in 2022-10, with the labels that each got.

#127 feat (declaritive lib): implement consistency check
  operator/pkg/declarative/reconciler.go
  operator/pkg/types/declaritive.go
Labels: lgtm, size/L

#125 Create CLI / Lifecycle-Manager Integration Test
  .github/workflows/ci.yml
  tests/smoke/.gitignore
  tests/smoke/Makefile
  tests/smoke/README.md
  tests/smoke/go.mod
  tests/smoke/go.sum
  tests/smoke/smoke_test.go
Labels: size/XL, lgtm

#126 add initial tests for state check - ensures resilience to .spec .config and spec.crds
  operator/controllers/manifest_controller_test.go
  operator/controllers/suite_test.go
  operator/internal/pkg/prepare/deploy.go
  operator/internal/pkg/util/util.go
  operator/main.go
  operator/pkg/declarative/reconciler.go
Labels: lgtm, size/L

#128 update client-go dependencies
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/M

#130 refactor: manifest library interface
  operator/controllers/manifest_controller.go
  operator/controllers/workers.go
  operator/internal/pkg/prepare/deploy.go
  operator/internal/pkg/util/util.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
Labels: lgtm, size/L

#132 refactor: Adjustments for KCP watcher and load tests
  operator/config/control-plane/kustomization.yaml
  operator/config/control-plane/patches/gateway_delete.yaml
  operator/config/istio/ap.yaml
  operator/config/istio/gateway.yaml
  operator/config/istio/kustomization.yaml
  operator/config/istio/patches/istio_namespace_labels.yaml
  operator/config/istio/virtual_service.yaml
  operator/config/load_test/kustomization.yaml
  operator/config/load_test/patches/adjust_resources_in_deployment.yaml
  operator/config/manager/metrics_service.yaml
  operator/config/watcher/kustomization.yaml
  operator/config/watcher/operator_v1alpha1_watcher.yaml
  operator/config/watcher/watcher_service_patch.yaml
  operator/controllers/manifest_controller.go
  operator/main.go
Labels: lgtm, size/L

#131 docs: adjust documentation for current implementation
  README.md
  operator/config/samples/operator_v1alpha1_manifest.yaml
  operator/go.mod
  operator/go.sum
  operator/main.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
Labels: lgtm, size/L

#129 Enhance declarative pkg
  operator/controllers/manifest_controller.go
  operator/go.mod
  operator/go.sum
  operator/internal/pkg/util/util.go
  operator/pkg/declarative/options.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/declarative/resolver.go
  operator/pkg/declarative/resolver_test.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/repo.go
  operator/pkg/resource/operations.go
  operator/pkg/types/resolver.go
  operator/pkg/util/util.go
  tests/smoke/go.mod
  tests/smoke/go.sum
Labels: lgtm, size/L

#140 cache rendered manifest for helm
  operator/Makefile
  operator/config/samples/operator_v1alpha1_manifest.yaml
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_controller_helper_test.go
  operator/controllers/manifest_controller_test.go
  operator/controllers/suite_test.go
  operator/controllers/test_samples/compressed.tgz
  operator/internal/pkg/prepare/deploy.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/descriptor/parse.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
  operator/pkg/util/util.go
Labels: size/XL, lgtm

#134 adjust configuartion based on load test finding
  operator/config/control-plane/kustomization.yaml
  operator/config/default/kustomization.yaml
  operator/config/default/patches/watcher_service_patch.yaml
  operator/config/load_test/kustomization.yaml
  operator/config/load_test/patches/adjust_resources_in_deployment.yaml
  operator/config/manager/manager.yaml
  operator/config/watcher/kustomization.yaml
  operator/config/watcher/operator_v1alpha1_watcher.yaml
  operator/go.mod
  operator/go.sum
  operator/main.go
  operator/pkg/manifest/client.go
Labels: lgtm, size/L

#145 feat: implement remote cluster info caching for remote clusters
  operator/api/v1alpha1/manifest_types.go
  operator/controllers/client_cache_manager.go
  operator/controllers/manifest_controller.go
  operator/controllers/manifest_controller_helper_test.go
  operator/controllers/manifest_controller_test.go
  operator/controllers/suite_test.go
  operator/internal/pkg/custom/verify.go
  operator/internal/pkg/prepare/deploy.go
  operator/internal/pkg/util/util.go
  operator/pkg/custom/client.go
  operator/pkg/custom/client_cache.go
  operator/pkg/custom/function.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/helm_client_cache.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/repo.go
  operator/pkg/rest/getter.go
  operator/pkg/types/cache.go
  operator/pkg/types/installs.go
  operator/pkg/util/util.go
Labels: lgtm, size/XXL

#152 fix: make helm cache optional
  operator/pkg/manifest/operations.go
Labels: lgtm, size/S
