Repository kyma-project/module-manager, pull requests merged in 2022-08, with the labels that each got.

#56 feat | refactor: listener + fix lint errors
  operator/.golangci.yaml
  operator/Makefile
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/manifest_types.go
  operator/api/v1alpha1/manifest_webhook.go
  operator/api/v1alpha1/webhook_suite_test.go
  operator/config/crd/bases/component.kyma-project.io_manifests.yaml
  operator/config/default/manager_auth_proxy_patch.yaml
  operator/config/manager/gateway.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/controllers/manifest_controller.go
  operator/controllers/suite_test.go
  operator/controllers/workers.go
  operator/go.mod
  operator/go.sum
  operator/internal/pkg/custom/verify.go
  operator/internal/pkg/prepare/deploy.go
  operator/internal/pkg/util/manifest.go
  operator/main.go
  operator/pkg/crd/operations.go
  operator/pkg/custom/client.go
  operator/pkg/custom/function.go
  operator/pkg/custom/status.go
  operator/pkg/descriptor/parse.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/repo.go
  operator/pkg/ratelimit/jitter.go
  operator/pkg/ratelimit/jitter_test.go
  operator/pkg/types/codec.go
  operator/pkg/types/installs.go
  operator/pkg/util/util.go
Labels: lgtm, size/XXL

#57 fix: install path and condition
  operator/controllers/manifest_controller.go
  operator/pkg/util/util.go
Labels: lgtm, size/M

#59 feat: cleanup resource, crds and refactor interface
  operator/api/v1alpha1/manifest_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/component.kyma-project.io_manifests.yaml
  operator/controllers/manifest_controller.go
  operator/controllers/workers.go
  operator/internal/pkg/custom/verify.go
  operator/internal/pkg/prepare/deploy.go
  operator/internal/pkg/util/manifest.go
  operator/main.go
  operator/pkg/custom/client.go
  operator/pkg/custom/function.go
  operator/pkg/custom/status.go
  operator/pkg/manifest/operations.go
  operator/pkg/resource/operations.go
  operator/pkg/types/custom_state.go
Labels: lgtm, size/L

#64 Adapt Makefile for Image build
  operator/Makefile
Labels: lgtm, size/XS

#65 fix: manifest reconciliation issues
  operator/.golangci.yaml
  operator/api/v1alpha1/groupversion_info.go
  operator/config/crd/bases/component.kyma-project.io_manifests.yaml
  operator/config/samples/component_v1alpha1_manifest.yaml
  operator/controllers/manifest_controller.go
  operator/internal/pkg/prepare/deploy.go
  operator/main.go
  operator/pkg/descriptor/parse.go
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/repo.go
  operator/pkg/types/codec.go
  operator/pkg/types/installs.go
Labels: lgtm, size/L

#70 fix: helm repo update for local chart installations
  operator/pkg/manifest/operations.go
  operator/pkg/manifest/repo.go
Labels: lgtm, size/S

#73 fix empty config.yaml
  operator/internal/pkg/prepare/deploy.go
Labels: lgtm, size/M

#67 feat(template-operator): add boiler plate for declarative pattern
  operator/controllers/manifest_controller.go
  operator/go.mod
  operator/go.sum
  operator/pkg/declarative/options.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
  operator/pkg/types/declaritive.go
  operator/pkg/types/installs.go
  operator/pkg/types/zz_generated.deepcopy.go
  operator/pkg/util/util.go
Labels: size/XL, lgtm

#74 rename kyma-operator => lifecycle-manager
  operator/config/manager/gateway.yaml
  operator/main.go
  operator/pkg/labels/component_labels.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
Labels: lgtm, size/S, do-not-merge/hold

#76 refactor: rename group component.kyma-project.io => operator.kyma-project.io
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/manifest_webhook.go
  operator/config/crd/bases/operator.kyma-project.io_manifests.yaml
  operator/config/crd/bases/sample_crd.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd/patches/cainjection_in_manifests.yaml
  operator/config/crd/patches/webhook_in_manifests.yaml
  operator/config/rbac/manifest_editor_role.yaml
  operator/config/rbac/manifest_viewer_role.yaml
  operator/config/rbac/role.yaml
  operator/config/samples/operator_v1alpha1_manifest.yaml
  operator/config/webhook/manifests.yaml
  operator/controllers/manifest_controller.go
  operator/pkg/labels/component_labels.go
Labels: lgtm, size/M

#79 feat: declarative implicit chart handling and other options
  operator/pkg/declarative/options.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/types/declaritive.go
  operator/pkg/types/installs.go
  operator/pkg/types/resolver.go
  operator/pkg/types/zz_generated.deepcopy.go
Labels: lgtm, size/L

#80 refactor: introduce flag types + rename declarative options
  operator/pkg/declarative/options.go
  operator/pkg/types/installs.go
  operator/pkg/types/resolver.go
Labels: lgtm, size/S
