Repository kyma-project/module-manager, pull requests merged in 2022-09, with the labels that each got.

#82 Upgrade listener dependency incl. linting issues fix
  operator/controllers/manifest_controller.go
  operator/go.mod
  operator/go.sum
  operator/pkg/declarative/reconciler.go
  operator/pkg/types/installs.go
Labels: lgtm, size/L

#83 upgrade kustomize and lint
  operator/Makefile
Labels: lgtm, size/XS

#85 Update image 6ba23a71
  operator/config/manager/kustomization.yaml
Labels: lgtm, size/XS

#86 Move Prometheus and Istio out of default
  operator/config/default/kustomization.yaml
  operator/config/istio/gateway.yaml
  operator/config/istio/virtual_service.yaml
  operator/config/manager/gateway.yaml
  operator/config/manager/manager.yaml
Labels: lgtm, size/M

#87 Fix wrong kustomization of istio resources
  operator/config/istio/kustomization.yaml
  operator/config/manager/kustomization.yaml
Labels: lgtm, size/XS

#88 fix: replace kustomize depracated 'bases' and unnecessary lines
  operator/config/default/kustomization.yaml
  operator/config/manager/kustomization.yaml
Labels: lgtm, size/XS

#89 feat: local cluster installation of manifest resources
  operator/.golangci.yaml
  operator/api/v1alpha1/manifest_types.go
  operator/config/crd/bases/operator.kyma-project.io_manifests.yaml
  operator/config/samples/operator_v1alpha1_manifest.yaml
  operator/controllers/manifest_controller.go
  operator/internal/pkg/custom/verify.go
  operator/internal/pkg/prepare/deploy.go
  operator/pkg/custom/client.go
  operator/pkg/custom/function.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/operations.go
Labels: lgtm, size/L

#90 enable crd for Kustomize build
  operator/config/default/kustomization.yaml
Labels: lgtm, size/XS

#93 fix various error message formats
  operator/pkg/declarative/reconciler.go
Labels: lgtm, size/S

#91 add common label
  operator/config/default/commonlabels_override.yaml
  operator/config/default/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/prometheus/monitor.yaml
  operator/config/rbac/auth_proxy_service.yaml
  operator/config/webhook/service.yaml
Labels: lgtm, size/M

#97 module-manager: WatcherCR initial setup
  operator/config/default/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/watcher/kustomization.yaml
  operator/config/watcher/watcher.yaml
  operator/config/watcher/watcher_service_patch.yaml
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/L

#98 feat: wait for namespace resource and fix chart timeout
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
  operator/pkg/util/util.go
Labels: lgtm, size/L

#100 upgrade: watcher resource and dependencies
  operator/config/watcher/watcher.yaml
  operator/controllers/manifest_controller.go
  operator/go.mod
  operator/go.sum
  operator/pkg/declarative/reconciler.go
Labels: lgtm, size/M

#103 Fix/Standardize kustomization Rendering
  operator/config/certmanager/kustomization.yaml
  operator/config/default/manager_config_patch.yaml
  operator/config/istio/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/prometheus/kustomization.yaml
  operator/config/webhook/kustomization.yaml
Labels: lgtm, size/S

#106 Standardize kustomize
  operator/.gitignore
  operator/Makefile
  operator/config/default/manager_auth_proxy_patch.yaml
  operator/config/manager/kustomization.yaml
Labels: lgtm, size/S

#107 fix: deployment and re-introduce default ports
  operator/Dockerfile
  operator/config/crd/kustomization.yaml
  operator/config/default/kustomization.yaml
  operator/config/istio/virtual_service.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/kustomization.yaml
  operator/config/watcher/watcher.yaml
  operator/main.go
Labels: lgtm, size/M

#105 Add Labels which are needed by Watcher
  operator/go.sum
  operator/internal/pkg/prepare/deploy.go
  operator/pkg/labels/component_labels.go
Labels: lgtm, size/S

#111 fix wrong webhook configuration api paths
  operator/api/v1alpha1/manifest_webhook.go
  operator/config/webhook/manifests.yaml
Labels: lgtm, size/XS

#112 Fix webhook paths
  operator/internal/pkg/prepare/deploy.go
Labels: lgtm, size/S

#115 fix: Handle empty spec.config
  operator/config/crd/bases/operator.kyma-project.io_manifests.yaml
  operator/internal/pkg/prepare/deploy.go
  operator/pkg/types/installs.go
Labels: lgtm, size/S

#117 fix: e2e fixes for 2 cluster setup
  operator/config/default/kustomization.yaml
  operator/internal/pkg/prepare/deploy.go
  operator/pkg/custom/client.go
  operator/pkg/declarative/reconciler.go
  operator/pkg/manifest/client.go
  operator/pkg/manifest/operations.go
  operator/pkg/resource/operations.go
  operator/pkg/util/util.go
Labels: lgtm, size/L

#120 Update Manifest deployment resource + update client-go
  operator/config/manager/manager.yaml
  operator/go.mod
  operator/go.sum
  operator/pkg/manifest/client.go
Labels: lgtm, size/S

#122 chore: setup control plane deployment
  operator/Makefile
  operator/config/control-plane/kustomization.yaml
  operator/config/control-plane/patches/cainjection_in_manifests.yaml
  operator/config/control-plane/patches/certificate_name.yaml
  operator/config/control-plane/patches/gateway_delete.yaml
  operator/config/control-plane/patches/manager_webhook_patch.yaml
  operator/config/control-plane/patches/namespace_delete.yaml
  operator/config/control-plane/patches/namespace_replace.yaml
  operator/config/control-plane/patches/service_monitor.yaml
  operator/config/control-plane/patches/webhook_in_manifests.yaml
  operator/config/control-plane/patches/webhookcainjection_patch.yaml
Labels: lgtm, size/L
