Repository kyma-project/module-manager, pull requests merged in 2023-01, with the labels that each got.

#202 support dockerconfigjson secret for oci registry authentication
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  controllers/manifest_controller_helper_test.go
  controllers/manifest_controller_test.go
  controllers/oci_registry_test.go
  go.mod
  go.sum
  internal/pkg/prepare/deploy.go
  pkg/client/client_proxy.go
  pkg/declarative/v2/reconciler.go
  pkg/descriptor/parse.go
  pkg/test_samples/auth_secret.yaml
  pkg/types/installs.go
  pkg/types/zz_generated.deepcopy.go
  pkg/util/util.go
Labels: lgtm, size/XXL

#204 fix manifest parser ttl to be regularly cleaned up
  pkg/declarative/v2/inmemory_rendered.go
Labels: lgtm, size/XS

#206 update config for load test
  config/load_test/kustomization.yaml
  go.mod
  main.go
Labels: lgtm, size/S

#207 fix: resolving secret not working purely by label selector
  internal/manifest/v1alpha1/skr_client_lookup.go
  pkg/custom/client.go
Labels: lgtm, size/S

#208 remove namespace while cred secret lookup
  internal/manifest/v1alpha1/keychain.go
  internal/manifest/v1alpha1/keychain_test.go
  internal/manifest/v1alpha1/spec_resolver.go
Labels: lgtm, size/S

#209 fix: remote flag default value apply & readiness errs
  api/v1alpha1/manifest_types.go
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  internal/manifest/v1alpha1/ready_check.go
  pkg/custom/client.go
  pkg/types/installs.go
Labels: lgtm, size/M
